### ISSUE TITLE
InventoryCleaner crashes

### ISSUE THREAD

**Issue by GOAT-GOATERSON** [CIOCOLATA47/InventoryCleaner#1]
The game crashes when I click play in the launcher and it gives me this error message:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'inventorycleaner'!

It's 1.21

**Comment by CIOCOLATA47** [comment]
imma fix it

**Comment by GOAT-GOATERSON** [comment]
Awesome, thank you because I LOVE the mod

**Comment by CIOCOLATA47** [comment]
It should be fixed now
