### ISSUE TITLE
InventoryCleaner

### ISSUE THREAD

**Issue by spectre2409** [CIOCOLATA47/InventoryCleaner#2]
Mod doesn't seem to work, when I do the commands (`/ic additem <item>` or `/ic delitem <item>`) it doesn't change anything, I also can't find the `inventorycleaner.properties` file in the config folder.

**Comment by CIOCOLATA47** [comment]
could you tell me the version

**Comment by spectre2409** [comment]
InventoryCleaner 1.0.4 for Minecraft 1.20.2 with fabric

**Comment by CIOCOLATA47** [comment]
So the problem is that I didn't add the commands in that version you need to use a newer one

**Comment by spectre2409** [comment]
alright, I'll use a newer version, thanks you!
